electron/lint-roller

.circleci/config.yml

Currently macOS jobs aren't being executed, might be due to this, so switching it over.

build: use gen2 macOS executor

---

lib/markdown.ts
tests/electron-lint-markdown-links.spec.ts
tests/fixtures/ignorepaths
tests/fixtures/valid-cross-file-link.md

After some debugging, I've figured out the Windows issue I've been encountering.
Calling `URI.path` for a `file://` URI returns a string that starts with a leading slash, so for example:
```
"file:///c%3A/Users/test/some-file.md"
```
Would become:
```
"/C:/Users/test/some-file.md"
```
That path is *not* a valid Windows path, so calls to `fs.existsSync` etc. will fail even though that target Markdown file exists on disk.
After digging around a little in `vscode-uri`, I found that they have a separate [fsPath](https://github.com/microsoft/vscode-uri/blob/1af8b2576342c7e6deff4d4a2c2e6cdfda170ff2/src/uri.ts#L204) property which seems to behave how we actually want it to behave, returning a string like:
```
"C:\\Users\\test\\some-file.md"
```
While debugging this, I also found that there …

fix: use URI.fsPath to get valid Windows paths

---

README.md
bin/lint-markdown-standard.ts
lib/markdown.ts
package.json
tests/__snapshots__/electron-lint-markdown-standard.spec.ts.snap
tests/electron-lint-markdown-standard.spec.ts
tests/fixtures/clean.md
tests/fixtures/cleanable.md
tests/fixtures/dirty.md
tests/fixtures/ignorepaths
yarn.lock

Effectively recreates [`zeke/standard-markdown`](https://github.com/zeke/standard-markdown) inside this project. A couple of small pieces of code (`removeParensWrappingOrphanedObject`, `wrapOrphanObjectInParens`) are taken from there, and the test fixtures are from that project, with more test cases added.
Why? That project is not currently maintained (CI is non-operational), and the regexes to find code blocks are unfortunately not very robust. Things like spaces after the backticks, camelCase, an info string (text after the language identifier), etc will cause code blocks to be skipped in `standard-markdown`. This has become problematic in Electron since much of the docs uses code blocks with info strings for rich rendering on the website, causing many blocks to not be linted currently …

feat: lint JS in Markdown files with standard

---

bin/lint-markdown-ts-check.ts
tests/__snapshots__/electron-lint-markdown-ts-check.spec.ts.snap
tests/fixtures/ts-check.md

Flubbed the original implementation. This fix ensures that the line numbers in the `tsc` output are accurate, and that multiple `@ts-ignore` lines refer to the correct line.

fix: properly handle multiple @ts-ignore lines

---

bin/lint-markdown-ts-check.ts
tests/fixtures/ts-check.md

Prevents situations where the modified line ends up being `// comment // @ts-ignore` which `tsc` wouldn't pick up.

fix: replace previous line comment when inserting ts-ignore

---

bin/lint-markdown-ts-check.ts

Need a couple more modules for a clean lint run on `e/e`.

fix: add more modules for type checking

---

README.md
bin/lint-markdown-ts-check.ts
tests/__snapshots__/electron-lint-markdown-ts-check.spec.ts.snap
tests/fixtures/ts-check.md

Sometimes the code blocks in the Electron docs are snippets which use variables not defined in that snippet, and sometimes it would be too cluttered/repetitive to define them in each snippet. This change allows for those variables to be typed with `@ts-type={name:type}` without needing to initialize them, since they're only used for type checking.

feat: ts-type for type checking

---

bin/lint-markdown-ts-check.ts
tests/__snapshots__/electron-lint-markdown-ts-check.spec.ts.snap
tests/fixtures/ts-check.md

As pointed out by @itsananderson, `@ts-expect-error` is probably a better fit than `@ts-ignore` when type checking of code blocks, since it doesn't have the risk of going stale and ignoring a line incorrectly. In hindsight it would have been better to implement that from the start, but since `@ts-ignore` is already implemented, support both for now, and if `@ts-ignore` support is adding no value, remove it in the future.

feat: support ts-expect-error for type checking

---

bin/lint-markdown-ts-check.ts
lib/helpers.ts
package.json
tests/fixtures/ts-check.md
tests/helpers.spec.ts
yarn.lock

Properly parse `@ts-type` directives with curly braces in the types, like `@ts-type={ anObject: { aProp: string } }`.

fix: handle ts-type values with curly braces

---

README.md
bin/lint-markdown-ts-check.ts
tests/__snapshots__/electron-lint-markdown-ts-check.spec.ts.snap
tests/fixtures/ts-check.md

Needs #22 to land first.
Adds a `@ts-window-type={name:type}` directive for adding types to the global `Window` object, which some code examples in the Electron docs need for type checking.

feat: add ts-window-type for type checking code blocks

---

README.md
bin/lint-markdown-ts-check.ts
tests/__snapshots__/electron-lint-markdown-ts-check.spec.ts.snap
tests/fixtures/ts-check-clean.md
tests/fixtures/ts-check.md

~~Needs #23 to land first, which in turn needs #22 to land first.~~
Supports type checking TS code blocks, which perhaps ironically were not type checked before this change. Also introduces a `@ts-noisolate` directive to allow global augmentation in one code block to bleed into others, which can be useful to avoid reiterating types when a subsequent block uses ones defined earlier.

feat: type check TypeScript code blocks

---

bin/lint-markdown-standard.ts
bin/lint-markdown-ts-check.ts
lib/markdown.ts

Make this a bit more easily reused for usage in linting scripts in `e/e`. Marking it as 'feat' so it triggers a new release. While technically a breaking change, the internal helpers are exposed for convenience and no guarantee is made regarding their API stability.

feat: make getCodeBlocks more reusable

---

jest.config.js

CI on Windows fails intermittently due to test timeout, so bump this.

test: bump test timeout

---

package.json

This was both overly restrictive (TypeScript 5 works fine) and too low (min is 4.7), so correcting it. Needs at least TypeScript 4.7 due to the usage of the `--moduleDetection` flag.
https://github.com/electron/lint-roller/blob/0b3adf9f514f57b3efd5eb56045e0f7c7120956a/bin/lint-markdown-ts-check.ts#L59

chore: fix version of typescript peer dependency

---

package.json

The `typescript` package is only needed for `electron-lint-markdown-ts-check`, so mark it as an optional peer dependency.

fix: mark typescript as optional peer dependency

---

bin/lint-markdown-links.ts
tests/electron-lint-markdown-links.spec.ts
tests/fixtures/github-label-link.md

Some time last week something changed with GitHub's servers that causes `node-fetch` to get a 404 when fetching certain links (notably labels on a repo). Works fine with the global fetch in Node.js, so use that if available to work around the issue.
`node-fetch` will be dropped in a future breaking change anyway.

feat: use Node.js global fetch if available

---

configs/markdownlint.json
markdownlint-rules/emd002.js
tests/__snapshots__/electron-markdownlint.spec.ts.snap
tests/electron-lint-markdown-links.spec.ts
tests/electron-markdownlint.spec.ts
tests/fixtures/angle-brackets.md
tests/fixtures/escaped-angle-brackets.md
tests/fixtures/ignorepaths

MDX v3 doesn't play nice with opening angle brackets, so provide a rule to help us keep them out of the docs unless they're properly escaped.

feat: markdownlint rule to disallow opening angle brackets

---

.gitignore
configs/markdownlint.json
markdownlint-rules/emd003.mjs
package.json
tests/__snapshots__/electron-markdownlint.spec.ts.snap
tests/electron-markdownlint.spec.ts
tests/fixtures/curly-braces.md
tests/fixtures/escaped-curly-braces.md

[MDX v3 doesn't play nice with unescaped curly braces](https://mdxjs.com/docs/what-is-mdx/#expressions), so provide a rule to help us keep them out of the docs unless they're properly escaped.

feat: markdownlint rule to disallow opening curly braces

---

tests/electron-lint-markdown-links.spec.ts

Only Node.js 18+ is supported now so this check is not needed.

chore: remove unneeded Node.js version check in test

---

.lint-roller.schema.json
README.md
bin/lint-markdown-ts-check.ts
lib/helpers.ts
package.json
tests/__snapshots__/lint-roller-markdown-ts-check.spec.ts.snap
tests/fixtures/.lint-roller.json
tests/fixtures/custom-config.json
tests/fixtures/ts-check-custom-config.md
tests/fixtures/ts-check.md
tests/lint-roller-markdown-ts-check.spec.ts

This removes all Electron-specific bits from the `markdown-ts-check` binary so that it is generic and can be used for any project.
Marking to skip release as this is part of multiple breaking changes I want to ship as a single v2, so the final PR will trigger the major release.

feat!: rename ts-check binary and add config support [skip release]

---

README.md
bin/lint-markdown-ts-check.ts
tests/__snapshots__/lint-roller-markdown-ts-check.spec.ts.snap
tests/fixtures/ts-check.md
tests/lint-roller-markdown-ts-check.spec.ts

Chained on top of #56.
`@ts-expect-error` is a much better solution, so remove `@ts-ignore` as it's not providing any value.

chore!: remove @ts-ignore syntax [skip release]

---

README.md
bin/lint-markdown-links.ts
bin/lint-markdown-standard.ts
package.json
tests/__snapshots__/lint-roller-markdown-standard.spec.ts.snap
tests/lint-roller-markdown-links.spec.ts
tests/lint-roller-markdown-standard.spec.ts

Chained on top of #57.
The binaries which aren't Electron-specific (everything except `electron-markdownlint` which is just a wrapper to add our default rules) are renamed with `lint-roller-` prefix so that they're generic and aren't confusing to use in other projects.

chore!: rename binaries to be more generic

---

bin/markdownlint-cli-wrapper.ts
markdownlint-rules/index.js

This will let rules be easily used from this package in a config without listing each rule. In a future breaking version `electron-markdownlint` will be removed.

feat: export all markdownlint rules

---

jest.config.js
package.json
tests/__snapshots__/electron-markdownlint.spec.ts.snap
tests/__snapshots__/lint-roller-markdown-standard.spec.ts.snap
tests/__snapshots__/lint-roller-markdown-ts-check.spec.ts.snap
tests/electron-markdownlint.spec.ts
tests/helpers.spec.ts
tests/lint-roller-markdown-links.spec.ts
tests/lint-roller-markdown-standard.spec.ts
tests/lint-roller-markdown-ts-check.spec.ts
tsconfig.json
yarn.lock

`vitest` is effectively a drop-in for `jest`. It's faster, and works better with TypeScript. Most significantly, it works well with ESM, while Jest is currently a headache to get working with ESM (and considers its support experimental).

test: switch to vitest

---

configs/markdownlint.json
markdownlint-rules/emd004.js
markdownlint-rules/index.js
tests/__snapshots__/electron-markdownlint.spec.ts.snap
tests/electron-markdownlint.spec.ts
tests/fixtures/angle-brackets.md
tests/fixtures/newline-in-link-text.md

Adds a `markdownlint` rule to disallow newlines in link text which would trigger a Docusaurus bug (https://github.com/facebook/docusaurus/issues/9048).

feat: markdownlint rule to disallow newline in link text

---

bin/lint-markdown-api-history.ts
tests/fixtures/api-history-description-invalid.md
tests/fixtures/api-history-format-invalid.md
tests/fixtures/api-history-heading-missing.md
tests/fixtures/api-history-placement-invalid.md
tests/fixtures/api-history-schema-invalid.md
tests/fixtures/api-history-string-invalid.md
tests/fixtures/api-history-valid.md
tests/fixtures/api-history-yaml-invalid.md
tests/lint-roller-markdown-api-history.spec.ts

Resolves: #78
Throws error if description field is not surrounded by double quotation marks.
@dsanders11 @erickzhao @VerteDinde

feat(api-history): `--check-descriptions`

---

package.json
tests/lint-roller-markdown-links.spec.ts
yarn.lock

Also a minor tweak to `tests/lint-roller-markdown-links.spec.ts` to avoid repeating`.toString('utf-8')` unnecessarily.

chore: update vitest

---

.markdownlint-cli2.jsonc
.markdownlint.json
package.json
tests/__snapshots__/markdownlint-cli2.spec.ts.snap
tests/markdownlint-cli2.spec.ts
yarn.lock

I got too overzealous with #91 and also removed test coverage. 🤦
This also downgrades to `markdownlint@0.34.0` (via `markdownlint-cli2@^0.13.0`) as the 0.35.0 release has a breaking change for our custom rules which needs to be rectified in a follow-up PR.

chore: restore markdownlint test coverage

---

markdownlint-rules/emd002.mjs
markdownlint-rules/emd003.mjs
markdownlint-rules/emd004.js
package.json
yarn.lock

The `filterTokens` helper went away and `addError` is just a very thing wrapper on top of `onError` so refactor to not use any of `markdownlint/helpers`, which should make these more robust to future version changes.
Skipping release so that this can go in with the breaking v3 changes.

feat: custom rule compat with markdownlint 0.35 [skip release]

---

.github/workflows/test.yml

The workflows are structured such that the release workflow (which triggers on push to `main`) also calls the test workflow (so that it can ensure tests pass before releasing). This currently leads to tests running 2x on `main`, so remove the redundant trigger.

ci: remove test workflow trigger on push

---

.github/workflows/release.yml
.github/workflows/test.yml

Picks up improvements from the workflows on `electron/windows-sign` which required a bit of tweaking to get a successful publish.

ci: fix GHA workflows

---

package.json
vitest.config.ts
yarn.lock

build(dev-deps): update vitest to 3.0.6

---

.github/workflows/test.yml
package.json
yarn.lock

As in title. Ensures we're compatible with the latest `markdownlint-cli2`. Also bumps the Node.js 22 version past the `require(esm)` change to confirm compatibility there as previous versions of `markdownlint-cli2` couldn't handle that change.

build(dev-deps): update markdownlint-cli2 to 0.17.2

---

README.md

Relic from the past, `img.shields.io` docs point you to use `https://` for these badge URLs.

docs: switch badge URL to HTTPS in README

---

package.json
yarn.lock

Fast follow-up to #118 because a new release happened to come out right after I created that. 😀

build(dev-deps): update markdownlint-cli2 to 0.18.0

---

bin/lint-markdown-links.ts
tests/fixtures/absolute-internal-link.md
tests/fixtures/ignorepaths
tests/lint-roller-markdown-links.spec.ts

Absolute links are problematic since they only work from the correct working directory, while a user might open the Markdown file from any number of locations. Adds a `--allow-absolute-links` option as an escape hatch for this behavior.

feat(lint-markdown-links): disallow absolute links

---

bin/lint-markdown-api-history.ts
bin/lint-markdown-links.ts
bin/lint-markdown-standard.ts
bin/lint-markdown-ts-check.ts

Turns out `process.argv[1]` can be a symlink in `.bin` for these scripts. Node.js is working on adding `import.meta.main` which will be the proper way to do this check in the future, but until then we can resolve the symlink to ensure this works correctly.

fix: resolve symlinks when checking if script is entrypoint
